# Generated by Django 5.2.5 on 2025-08-26 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
